# Generated by Django 5.2.4 on 2025-08-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prasadam_pass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='is_given',
            new_name='is_checked_in',
        ),
    ]
