# Generated by Django 5.2.4 on 2025-08-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prasadam_pass', '0002_rename_is_given_registration_is_checked_in'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
    ]
