# Generated by Django 5.2.4 on 2025-08-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prasadam_pass', '0003_alter_registration_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='prasad_quantity',
        ),
    ]
