# Generated by Django 5.2.4 on 2025-08-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasadam_pass', '0004_remove_registration_prasad_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slots',
            field=models.CharField(default='Morning, Evening', help_text="Comma-seperated time slots (e.g. '6PM to 7PM, 7PM to 8PM, 8PM to 9PM' or 'Morning, Evening')", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='slot',
            field=models.CharField(default='Morning', max_length=25),
            preserve_default=False,
        ),
    ]
